# Changes here will be overwritten by Copier
_commit: v1.0
_src_path: gh:igembitsgoa/igem-wiki-starter
author: Malte Schwerin
email: malte.schwerin@rwth-aachen.de
iGEM_official_team_name: Aachen
iGEM_team_name: Aachen
year: 2021