 
name: Integration Test

on:
  - pull_request
  - push
  
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0


      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm test

      - name: Github Fix
        run: sh utils/github.io_fix.sh

      - name: Preprocess
        run: npm run prestart

      - name: Build
        run: npm run-script build
